# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 0.6
  - 0.7
  - 1.0
  - 1.1-
  - nightly

notifications:
  email: false

after_success:
  - julia -e '@static if VERSION â‰¥ v"0.7"; using Pkg; end;
      cd(Pkg.dir("UnitfulAtomic"));
      Pkg.add("Coverage");
      using Coverage;
      Codecov.submit(process_folder());
      Coveralls.submit(process_folder())'
